/**
 * 独立变量项（非组合），支持各数值类型的标量变量及其物理单位扩展。
 * Independent variable items (non-combination), supporting scalar variables for all numeric types and their physical unit extensions.
 */
package fuookami.ospf.kotlin.core.variable

import fuookami.ospf.kotlin.math.*
import fuookami.ospf.kotlin.math.algebra.concept.NumberField
import fuookami.ospf.kotlin.math.algebra.concept.RealNumber
import fuookami.ospf.kotlin.math.algebra.concept.RealNumberConstants
import fuookami.ospf.kotlin.math.algebra.number.*
import fuookami.ospf.kotlin.math.algebra.value_range.*
import fuookami.ospf.kotlin.quantities.quantity.Quantity

/**
 * 独立变量项的密封基类，维度为 0，标识符由 IdentifierGenerator 生成。
 * Sealed base class for independent variable items with dimension 0 and identifier generated by IdentifierGenerator.
 *
 * @property type 变量类型 / Variable type
 * @property name 变量名称 / Variable name
 * @property constants 数值类型常量 / Numeric type constants
 */
sealed class IndependentVariableItem<T, Type : VariableType<T>>(
    type: Type,
    name: String,
    constants: RealNumberConstants<T>
) : AbstractVariableItem<T, Type>(type, name, constants) where T : RealNumber<T>, T : NumberField<T> {
    override val dimension = 0
    override val identifier = IdentifierGenerator.gen()
    override val index = 0
    override val vectorView = intArrayOf(0)

    override fun belongsTo(combination: VariableCombination<*, *, *>): Boolean {
        return false
    }
}

typealias Variable<Type> = IndependentVariableItem<*, Type>
typealias QuantityVariable<Type> = Quantity<IndependentVariableItem<*, Type>>

class BinVar(name: String = "") : IndependentVariableItem<UInt8, Binary>(Binary, name, UInt8)
class TerVar(name: String = "") : IndependentVariableItem<UInt8, Ternary>(Ternary, name, UInt8)
class BTerVar(name: String = "") : IndependentVariableItem<Int8, BalancedTernary>(BalancedTernary, name, Int8)
class PctVar(name: String = "") : IndependentVariableItem<Flt64, Percentage>(Percentage, name, Flt64)
class IntVar(name: String = "") : IndependentVariableItem<Int64, Integer>(Integer, name, Int64)
class UIntVar(name: String = "") : IndependentVariableItem<UInt64, UInteger>(UInteger, name, UInt64)
class RealVar(name: String = "") : IndependentVariableItem<Flt64, Continuous>(Continuous, name, Flt64)
class URealVar(name: String = "") : IndependentVariableItem<Flt64, UContinuous>(UContinuous, name, Flt64)

typealias QuantityBinVar = QuantityVariable<Binary>
typealias QuantityTerVar = QuantityVariable<Ternary>
typealias QuantityBTerVar = QuantityVariable<BalancedTernary>
typealias QuantityPctVar = QuantityVariable<Percentage>
typealias QuantityIntVar = QuantityVariable<Integer>
typealias QuantityUIntVar = QuantityVariable<UInteger>
typealias QuantityRealVar = QuantityVariable<Continuous>
typealias QuantityURealVar = QuantityVariable<UContinuous>
