/**
 * 独立变量项（非组合），支持各数值类型的标量变量及其物理单位扩展。
 * Independent variable items (non-combination), supporting scalar variables for all numeric types and their physical unit extensions.
*/
package fuookami.ospf.kotlin.core.variable

import fuookami.ospf.kotlin.math.*
import fuookami.ospf.kotlin.math.algebra.number.*
import fuookami.ospf.kotlin.math.algebra.concept.*
import fuookami.ospf.kotlin.math.algebra.value_range.*
import fuookami.ospf.kotlin.quantities.quantity.Quantity

/**
 * 独立变量项的密封基类，维度为 0，标识符由 IdentifierGenerator 生成。
 * Sealed base class for independent variable items with dimension 0 and identifier generated by IdentifierGenerator.
 *
 * @param T 数值类型 / The number type
 * @param Type 变量类型 / The variable type
 * @property type 变量类型 / Variable type
 * @property name 变量名称 / Variable name
 * @property constants 数值类型常量 / Numeric type constants
*/
sealed class IndependentVariableItem<T, Type : VariableType<T>>(
    type: Type,
    name: String,
    constants: RealNumberConstants<T>
) : AbstractVariableItem<T, Type>(type, name, constants) where T : RealNumber<T>, T : NumberField<T> {
    override val dimension = 0
    override val identifier = IdentifierGenerator.gen()
    override val index = 0
    override val vectorView = intArrayOf(0)

    override fun belongsTo(combination: VariableCombination<*, *, *>): Boolean {
        return false
    }
}

/** 独立变量项类型别名 / Independent variable item type alias */
typealias Variable<Type> = IndependentVariableItem<*, Type>

/** 物理量独立变量项类型别名 / Quantity independent variable item type alias */
typealias QuantityVariable<Type> = Quantity<IndependentVariableItem<*, Type>>

/**
 * 二值标量变量 / Binary scalar variable
 *
 * @param name 变量名称 / Variable name
*/
class BinVar(name: String = "") : IndependentVariableItem<UInt8, Binary>(Binary, name, UInt8)

/**
 * 三值标量变量 / Ternary scalar variable
 *
 * @param name 变量名称 / Variable name
*/
class TerVar(name: String = "") : IndependentVariableItem<UInt8, Ternary>(Ternary, name, UInt8)

/**
 * 平衡三值标量变量 / Balanced ternary scalar variable
 *
 * @param name 变量名称 / Variable name
*/
class BTerVar(name: String = "") : IndependentVariableItem<Int8, BalancedTernary>(BalancedTernary, name, Int8)

/**
 * 百分比标量变量 / Percentage scalar variable
 *
 * @param name 变量名称 / Variable name
*/
class PctVar(name: String = "") : IndependentVariableItem<Flt64, Percentage>(Percentage, name, Flt64)

/**
 * 整数标量变量 / Integer scalar variable
 *
 * @param name 变量名称 / Variable name
*/
class IntVar(name: String = "") : IndependentVariableItem<Int64, Integer>(Integer, name, Int64)

/**
 * 无符号整数标量变量 / Unsigned integer scalar variable
 *
 * @param name 变量名称 / Variable name
*/
class UIntVar(name: String = "") : IndependentVariableItem<UInt64, UInteger>(UInteger, name, UInt64)

/**
 * 连续标量变量 / Continuous scalar variable
 *
 * @param name 变量名称 / Variable name
*/
class RealVar(name: String = "") : IndependentVariableItem<Flt64, Continuous>(Continuous, name, Flt64)

/**
 * 无符号连续标量变量 / Unsigned continuous scalar variable
 *
 * @param name 变量名称 / Variable name
*/
class URealVar(name: String = "") : IndependentVariableItem<Flt64, UContinuous>(UContinuous, name, Flt64)

/** 物理量二值标量变量 / Quantity binary scalar variable */
typealias QuantityBinVar = QuantityVariable<Binary>

/** 物理量三值标量变量 / Quantity ternary scalar variable */
typealias QuantityTerVar = QuantityVariable<Ternary>

/** 物理量平衡三值标量变量 / Quantity balanced ternary scalar variable */
typealias QuantityBTerVar = QuantityVariable<BalancedTernary>

/** 物理量百分比标量变量 / Quantity percentage scalar variable */
typealias QuantityPctVar = QuantityVariable<Percentage>

/** 物理量整数标量变量 / Quantity integer scalar variable */
typealias QuantityIntVar = QuantityVariable<Integer>

/** 物理量无符号整数标量变量 / Quantity unsigned integer scalar variable */
typealias QuantityUIntVar = QuantityVariable<UInteger>

/** 物理量连续标量变量 / Quantity continuous scalar variable */
typealias QuantityRealVar = QuantityVariable<Continuous>

/** 物理量无符号连续标量变量 / Quantity unsigned continuous scalar variable */
typealias QuantityURealVar = QuantityVariable<UContinuous>
