<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>io.github.fuookami.ospf.kotlin.core.plugin</groupId>
        <artifactId>ospf-kotlin-core-plugin</artifactId>
        <version>1.1.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <name>ospf-kotlin-core-plugin-gurobi</name>
    <artifactId>ospf-kotlin-core-plugin-gurobi${ospf.kotlin.artifact.suffix}</artifactId>

    <dependencies>
        <dependency>
            <groupId>gurobi</groupId>
            <artifactId>gurobi</artifactId>
            <version>1.0.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>io.github.fuookami.ospf.kotlin.core.plugin</groupId>
            <artifactId>ospf-kotlin-core-plugin-scip</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>scip</groupId>
            <artifactId>jscip</artifactId>
            <version>1.0.0</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <sourceDirectory>src/main</sourceDirectory>
        <testSourceDirectory>src/test</testSourceDirectory>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <executions>
                    <execution>
                        <id>gurobi-integration-test</id>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                        <configuration>
                            <forkCount>1</forkCount>
                            <systemPropertyVariables>
                                <ospf.gurobi.suppressOutput>true</ospf.gurobi.suppressOutput>
                            </systemPropertyVariables>
                            <includes>
                                <include>**/*IT.class</include>
                            </includes>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
