@file:OptIn(kotlin.time.ExperimentalTime::class)

package fuookami.ospf.kotlin.framework.solver

import fuookami.ospf.kotlin.core.solver.output.SolverOutput
import fuookami.ospf.kotlin.core.solver.output.SolvingStatusCallBack
import fuookami.ospf.kotlin.math.symbol.adapter.flt64.QuadraticInequality
import fuookami.ospf.kotlin.core.model.basic.RegistrationStatusCallBack
import fuookami.ospf.kotlin.core.variable.AbstractVariableItem
import fuookami.ospf.kotlin.utils.functional.Ret
import fuookami.ospf.kotlin.math.algebra.number.Flt64
import kotlinx.coroutines.DelicateCoroutinesApi
import kotlinx.coroutines.GlobalScope
import kotlinx.coroutines.future.future
import java.util.concurrent.CompletableFuture
import kotlin.time.Duration
import fuookami.ospf.kotlin.core.model.mechanism.Constraint
import fuookami.ospf.kotlin.core.model.mechanism.Linear
import fuookami.ospf.kotlin.core.model.mechanism.LinearMetaModel
import fuookami.ospf.kotlin.core.model.mechanism.Quadratic
import fuookami.ospf.kotlin.core.model.mechanism.QuadraticMetaModel
import fuookami.ospf.kotlin.core.solver.output.FeasibleSolverOutput
import fuookami.ospf.kotlin.math.symbol.inequality.LinearInequality

interface LinearBendersDecompositionSolver {
    val name: String

    suspend fun solveMaster(
        name: String,
        metaModel: LinearMetaModel<fuookami.ospf.kotlin.math.algebra.number.Flt64>,
        toLogModel: Boolean = false,
        registrationStatusCallBack: RegistrationStatusCallBack? = null,
        solvingStatusCallBack: SolvingStatusCallBack? = null
    ): Ret<SolverOutput>

    suspend fun solveMaster(
        metaModel: LinearMetaModel<fuookami.ospf.kotlin.math.algebra.number.Flt64>,
        options: FrameworkSolveOptions = FrameworkSolveOptions()
    ): Ret<SolverOutput> {
        return solveMaster(
            name = options.solveName(metaModel.name),
            metaModel = metaModel,
            toLogModel = options.toLogModel,
            registrationStatusCallBack = options.registrationStatusCallBack,
            solvingStatusCallBack = options.solvingStatusCallBack
        )
    }

    @OptIn(DelicateCoroutinesApi::class)
    fun solveMasterAsync(
        name: String,
        metaModel: LinearMetaModel<fuookami.ospf.kotlin.math.algebra.number.Flt64>,
        toLogModel: Boolean = false,
        registrationStatusCallBack: RegistrationStatusCallBack? = null,
        solvingStatusCallBack: SolvingStatusCallBack? = null
    ): CompletableFuture<Ret<SolverOutput>> {
        return GlobalScope.future {
            return@future this@LinearBendersDecompositionSolver.solveMaster(
                name = name,
                metaModel = metaModel,
                toLogModel = toLogModel,
                registrationStatusCallBack = registrationStatusCallBack,
                solvingStatusCallBack = solvingStatusCallBack
            )
        }
    }

    @OptIn(DelicateCoroutinesApi::class)
    fun solveMasterAsync(
        metaModel: LinearMetaModel<fuookami.ospf.kotlin.math.algebra.number.Flt64>,
        options: FrameworkSolveOptions = FrameworkSolveOptions()
    ): CompletableFuture<Ret<SolverOutput>> {
        return GlobalScope.future {
            return@future this@LinearBendersDecompositionSolver.solveMaster(
                metaModel = metaModel,
                options = options
            )
        }
    }

    /**
     * Sub Problem Solving Result (with cuts if fixed variables are provided)
     *
     * @property cuts           list of cuts generated by sub problem, if fixed variables are provided.
     * Otherwise, there should not be any fixed variables in the sub problem model. In other words, the fixed variables should be replaced with their values.
     */
    sealed interface LinearSubResult {
        val cuts: List<LinearInequality<fuookami.ospf.kotlin.math.algebra.number.Flt64>>?
    }

    data class LinearFeasibleResult(
        val result: FeasibleSolverOutput<fuookami.ospf.kotlin.math.algebra.number.Flt64>,
        val dualSolution: kotlin.collections.Map<Constraint<Flt64, Linear>, Flt64>,
        override val cuts: List<LinearInequality<fuookami.ospf.kotlin.math.algebra.number.Flt64>>?
    ) : LinearSubResult {
        val obj: Flt64 by result::obj
        val solution: List<fuookami.ospf.kotlin.math.algebra.number.Flt64> by result::solution
        val time: Duration by result::time
        val possibleBestObj by result::possibleBestObj
        val gap: Flt64 by result::gap
    }

    data class LinearInfeasibleResult(
        val farkasDualSolution: kotlin.collections.Map<Constraint<Flt64, Linear>, Flt64>,
        override val cuts: List<LinearInequality<fuookami.ospf.kotlin.math.algebra.number.Flt64>>?
    ) : LinearSubResult

    suspend fun solveSub(
        name: String,
        metaModel: LinearMetaModel<fuookami.ospf.kotlin.math.algebra.number.Flt64>,
        objectVariable: AbstractVariableItem<*, *>,
        fixedVariables: Map<AbstractVariableItem<*, *>, Flt64>,
        toLogModel: Boolean = false,
        registrationStatusCallBack: RegistrationStatusCallBack? = null,
        solvingStatusCallBack: SolvingStatusCallBack? = null
    ): Ret<LinearSubResult>

    suspend fun solveSub(
        metaModel: LinearMetaModel<fuookami.ospf.kotlin.math.algebra.number.Flt64>,
        objectVariable: AbstractVariableItem<*, *>,
        fixedVariables: Map<AbstractVariableItem<*, *>, Flt64>,
        options: FrameworkSolveOptions = FrameworkSolveOptions()
    ): Ret<LinearSubResult> {
        return solveSub(
            name = options.solveName(metaModel.name),
            metaModel = metaModel,
            objectVariable = objectVariable,
            fixedVariables = fixedVariables,
            toLogModel = options.toLogModel,
            registrationStatusCallBack = options.registrationStatusCallBack,
            solvingStatusCallBack = options.solvingStatusCallBack
        )
    }

    @OptIn(DelicateCoroutinesApi::class)
    fun solveSubAsync(
        name: String,
        metaModel: LinearMetaModel<fuookami.ospf.kotlin.math.algebra.number.Flt64>,
        objectVariable: AbstractVariableItem<*, *>,
        fixedVariables: Map<AbstractVariableItem<*, *>, Flt64>,
        toLogModel: Boolean = false,
        registrationStatusCallBack: RegistrationStatusCallBack? = null,
        solvingStatusCallBack: SolvingStatusCallBack? = null
    ): CompletableFuture<Ret<LinearSubResult>> {
        return GlobalScope.future {
            return@future this@LinearBendersDecompositionSolver.solveSub(
                name = name,
                metaModel = metaModel,
                objectVariable = objectVariable,
                fixedVariables = fixedVariables,
                toLogModel = toLogModel,
                registrationStatusCallBack = registrationStatusCallBack,
                solvingStatusCallBack = solvingStatusCallBack
            )
        }
    }

    @OptIn(DelicateCoroutinesApi::class)
    fun solveSubAsync(
        metaModel: LinearMetaModel<fuookami.ospf.kotlin.math.algebra.number.Flt64>,
        objectVariable: AbstractVariableItem<*, *>,
        fixedVariables: Map<AbstractVariableItem<*, *>, Flt64>,
        options: FrameworkSolveOptions = FrameworkSolveOptions()
    ): CompletableFuture<Ret<LinearSubResult>> {
        return GlobalScope.future {
            return@future this@LinearBendersDecompositionSolver.solveSub(
                metaModel = metaModel,
                objectVariable = objectVariable,
                fixedVariables = fixedVariables,
                options = options
            )
        }
    }
}

interface QuadraticBendersDecompositionSolver : LinearBendersDecompositionSolver {
    suspend fun solveMaster(
        name: String,
        metaModel: QuadraticMetaModel<fuookami.ospf.kotlin.math.algebra.number.Flt64>,
        toLogModel: Boolean = false,
        registrationStatusCallBack: RegistrationStatusCallBack? = null,
        solvingStatusCallBack: SolvingStatusCallBack? = null
    ): Ret<SolverOutput>

    suspend fun solveMaster(
        metaModel: QuadraticMetaModel<fuookami.ospf.kotlin.math.algebra.number.Flt64>,
        options: FrameworkSolveOptions = FrameworkSolveOptions()
    ): Ret<SolverOutput> {
        return solveMaster(
            name = options.solveName(metaModel.name),
            metaModel = metaModel,
            toLogModel = options.toLogModel,
            registrationStatusCallBack = options.registrationStatusCallBack,
            solvingStatusCallBack = options.solvingStatusCallBack
        )
    }

    @OptIn(DelicateCoroutinesApi::class)
    fun solveMasterAsync(
        name: String,
        metaModel: QuadraticMetaModel<fuookami.ospf.kotlin.math.algebra.number.Flt64>,
        toLogModel: Boolean = false,
        registrationStatusCallBack: RegistrationStatusCallBack? = null,
        solvingStatusCallBack: SolvingStatusCallBack? = null
    ): CompletableFuture<Ret<SolverOutput>> {
        return GlobalScope.future {
            return@future this@QuadraticBendersDecompositionSolver.solveMaster(
                name = name,
                metaModel = metaModel,
                toLogModel = toLogModel,
                registrationStatusCallBack = registrationStatusCallBack,
                solvingStatusCallBack = solvingStatusCallBack
            )
        }
    }

    @OptIn(DelicateCoroutinesApi::class)
    fun solveMasterAsync(
        metaModel: QuadraticMetaModel<fuookami.ospf.kotlin.math.algebra.number.Flt64>,
        options: FrameworkSolveOptions = FrameworkSolveOptions()
    ): CompletableFuture<Ret<SolverOutput>> {
        return GlobalScope.future {
            return@future this@QuadraticBendersDecompositionSolver.solveMaster(
                metaModel = metaModel,
                options = options
            )
        }
    }

    /**
     * Sub Problem Solving Result (with cuts if fixed variables are provided)
     *
     * @property linearCuts     list of linear cuts generated by sub problem, if fixed variables are provided.
     * @property quadraticCuts  list of quadratic cuts generated by sub problem, if fixed variables are provided.
     * Otherwise, there should not be any fixed variables in the sub problem model. In other words, the fixed variables should be replaced with their values.
     */
    sealed interface QuadraticSubResult {
        val linearCuts: List<LinearInequality<fuookami.ospf.kotlin.math.algebra.number.Flt64>>?
        val quadraticCuts: List<QuadraticInequality>?
    }

    data class QuadraticFeasibleResult(
        val result: FeasibleSolverOutput<fuookami.ospf.kotlin.math.algebra.number.Flt64>,
        val dualSolution: kotlin.collections.Map<Constraint<Flt64, Quadratic>, Flt64>,
        override val linearCuts: List<LinearInequality<fuookami.ospf.kotlin.math.algebra.number.Flt64>>?,
        override val quadraticCuts: List<QuadraticInequality>?,
    ) : QuadraticSubResult {
        val obj: Flt64 by result::obj
        val solution: List<fuookami.ospf.kotlin.math.algebra.number.Flt64> by result::solution
        val time: Duration by result::time
        val possibleBestObj by result::possibleBestObj
        val gap: Flt64 by result::gap
    }

    data class QuadraticInfeasibleResult(
        val farkasDualSolution: kotlin.collections.Map<Constraint<Flt64, Quadratic>, Flt64>,
        override val linearCuts: List<LinearInequality<fuookami.ospf.kotlin.math.algebra.number.Flt64>>?,
        override val quadraticCuts: List<QuadraticInequality>?,
    ) : QuadraticSubResult

    suspend fun solveSub(
        name: String,
        metaModel: QuadraticMetaModel<fuookami.ospf.kotlin.math.algebra.number.Flt64>,
        objectVariable: AbstractVariableItem<*, *>,
        fixedVariables: Map<AbstractVariableItem<*, *>, Flt64>,
        toLogModel: Boolean = false,
        registrationStatusCallBack: RegistrationStatusCallBack? = null,
        solvingStatusCallBack: SolvingStatusCallBack? = null
    ): Ret<QuadraticSubResult>

    suspend fun solveSub(
        metaModel: QuadraticMetaModel<fuookami.ospf.kotlin.math.algebra.number.Flt64>,
        objectVariable: AbstractVariableItem<*, *>,
        fixedVariables: Map<AbstractVariableItem<*, *>, Flt64>,
        options: FrameworkSolveOptions = FrameworkSolveOptions()
    ): Ret<QuadraticSubResult> {
        return solveSub(
            name = options.solveName(metaModel.name),
            metaModel = metaModel,
            objectVariable = objectVariable,
            fixedVariables = fixedVariables,
            toLogModel = options.toLogModel,
            registrationStatusCallBack = options.registrationStatusCallBack,
            solvingStatusCallBack = options.solvingStatusCallBack
        )
    }

    @OptIn(DelicateCoroutinesApi::class)
    fun solveSubAsync(
        name: String,
        metaModel: QuadraticMetaModel<fuookami.ospf.kotlin.math.algebra.number.Flt64>,
        objectVariable: AbstractVariableItem<*, *>,
        fixedVariables: Map<AbstractVariableItem<*, *>, Flt64>,
        toLogModel: Boolean = false,
        registrationStatusCallBack: RegistrationStatusCallBack? = null,
        solvingStatusCallBack: SolvingStatusCallBack? = null
    ): CompletableFuture<Ret<QuadraticSubResult>> {
        return GlobalScope.future {
            return@future this@QuadraticBendersDecompositionSolver.solveSub(
                name = name,
                metaModel = metaModel,
                objectVariable = objectVariable,
                fixedVariables = fixedVariables,
                toLogModel = toLogModel,
                registrationStatusCallBack = registrationStatusCallBack,
                solvingStatusCallBack = solvingStatusCallBack
            )
        }
    }

    @OptIn(DelicateCoroutinesApi::class)
    fun solveSubAsync(
        metaModel: QuadraticMetaModel<fuookami.ospf.kotlin.math.algebra.number.Flt64>,
        objectVariable: AbstractVariableItem<*, *>,
        fixedVariables: Map<AbstractVariableItem<*, *>, Flt64>,
        options: FrameworkSolveOptions = FrameworkSolveOptions()
    ): CompletableFuture<Ret<QuadraticSubResult>> {
        return GlobalScope.future {
            return@future this@QuadraticBendersDecompositionSolver.solveSub(
                metaModel = metaModel,
                objectVariable = objectVariable,
                fixedVariables = fixedVariables,
                options = options
            )
        }
    }
}


