package fuookami.ospf.kotlin.framework.csp1d.domain.material.model

import fuookami.ospf.kotlin.math.algebra.concept.RealNumber
import fuookami.ospf.kotlin.math.algebra.number.Flt64
import fuookami.ospf.kotlin.quantities.quantity.Quantity

/**
 * CSP1D 领域计算上下文 / CSP1D domain calculation context
 *
 * 提供单条记录级别的领域判断所需信息。
 * 用于 same unit length、same width、宽差、材质兼容等
 * 需要访问单条切割方案属性的扩展点。
 *
 * Provides information for domain-level judgment on individual records.
 * Used for same unit length, same width, width difference, material compatibility
 * extensions that need access to individual cutting plan properties.
 *
 * @param V 数值类型 / Numeric value type
 */
interface Csp1dDomainCalculationContext<V : RealNumber<V>> {
    /** 当前切割方案 / Current cutting plan */
    val plan: CuttingPlan<V>

    /** 方案索引 / Plan index */
    val planIndex: Int

    /** 方案所属物料 / Plan material */
    val material: Material<V> get() = plan.material

    /** 方案所属设备 ID / Plan machine ID */
    val machineId: String? get() = plan.machineId

    /** 方案切片列表 / Plan slices */
    val slices: List<CuttingPlanSlice<V>> get() = plan.slices

    /** 方案需求贡献 / Plan demand contributions */
    val demandContributions: List<CuttingPlanDemandContribution<V>> get() = plan.demandContributions

    /** 领域数值样本 / Domain value sample */
    val domainValueSample: V

    /** 转换为领域数值 / Convert to domain value */
    fun toDomainValue(value: Flt64): V

    /** 计算指定产品的需求贡献量 / Compute demand contribution for specified product */
    fun contributionFor(productId: String): Flt64?
}

/**
 * 简单领域计算上下文 / Simple domain calculation context
 *
 * Csp1dDomainCalculationContext 的默认实现，直接包装 CuttingPlan。
 *
 * Default implementation of Csp1dDomainCalculationContext, wrapping a CuttingPlan directly.
 *
 * @param V 数值类型 / Numeric value type
 */
data class SimpleDomainCalculationContext<V : RealNumber<V>>(
    override val plan: CuttingPlan<V>,
    override val planIndex: Int = 0,
    override val domainValueSample: V,
    private val domainValueConverter: (Flt64) -> V = { value -> convertSolverValue(domainValueSample, value) }
) : Csp1dDomainCalculationContext<V> {
    override fun toDomainValue(value: Flt64): V = domainValueConverter(value)

    override fun contributionFor(productId: String): Flt64? {
        return plan.demandContributions.find { it.product.id == productId }?.quantity?.value?.toFlt64()
    }
}

/**
 * CSP1D 领域策略接口 / CSP1D domain policy interface
 *
 * 允许下游注入领域计算/判断逻辑，如物料可行性、宽度判断、余料计算等。
 * 默认实现应保持现有行为。
 *
 * Allows downstream to inject domain calculation/judgment logic,
 * such as material feasibility, width judgment, rest material calculation.
 * Default implementation should preserve existing behavior.
 *
 * @param V 数值类型 / Numeric value type
 */
interface Csp1dDomainPolicy<V : RealNumber<V>> {
    /** 策略名称 / Policy name */
    val name: String

    /**
     * 是否接管宽度可行性判断 / Whether this policy takes over width feasibility judgment
     *
     * 默认 false，表示该 policy 的 isWidthFeasible() 仅作后置过滤，不影响原始 canCut 逻辑。
     * 设为 true 时，该 policy 会参与 widthFeasibilityCheckFromPolicies() 生成的宽度判断函数，
     * 替代原始 material.widthRange.canCut()。这允许放宽或收窄原始宽度范围。
     *
     * Default false: the policy's isWidthFeasible() only acts as a post-filter,
     * not affecting the original canCut logic.
     * Set to true: the policy participates in the width feasibility check function
     * generated by widthFeasibilityCheckFromPolicies(), replacing the original
     * material.widthRange.canCut(). This allows relaxing or narrowing the original width range.
     */
    val overridesWidthFeasibility: Boolean get() = false

    /**
     * 判断切割方案在给定上下文中是否可行 /
     * Check if cutting plan is feasible in the given context
     *
     * @param context 领域计算上下文 / Domain calculation context
     * @return true 表示可行 / true if feasible
     */
    fun isFeasible(context: Csp1dDomainCalculationContext<V>): Boolean = true

    /**
     * 判断切割方案在给定上下文中宽度是否可切 /
     * Check if cutting plan width is feasible in the given context
     *
     * @param context 领域计算上下文 / Domain calculation context
     * @return true 表示可切 / true if cuttable
     */
    fun isWidthFeasible(context: Csp1dDomainCalculationContext<V>): Boolean = true
}

/**
 * 默认 CSP1D 领域策略 / Default CSP1D domain policy
 *
 * 保持现有硬编码行为：所有方案都可行，所有宽度都可切。
 * 当 domainPolicies 为空列表时，行为与此策略等价。
 *
 * Preserves existing hard-coded behavior: all plans are feasible,
 * all widths are cuttable. When domainPolicies is an empty list,
 * behavior is equivalent to this policy.
 *
 * @param V 数值类型 / Numeric value type
 */
class DefaultCsp1dDomainPolicy<V : RealNumber<V>> : Csp1dDomainPolicy<V> {
    override val name: String = "default"

    override fun isFeasible(context: Csp1dDomainCalculationContext<V>): Boolean = true

    override fun isWidthFeasible(context: Csp1dDomainCalculationContext<V>): Boolean = true
}

/**
 * 判断一组领域策略是否全部认为方案可行 /
 * Check if all domain policies consider the plan feasible
 *
 * @param V 数值类型 / Numeric value type
 * @param policies 领域策略列表 / Domain policy list
 * @param context 领域计算上下文 / Domain calculation context
 * @return true 表示所有策略都认为可行 / true if all policies consider feasible
 */
fun <V : RealNumber<V>> allFeasible(
    policies: List<Csp1dDomainPolicy<V>>,
    context: Csp1dDomainCalculationContext<V>
): Boolean {
    return policies.all { it.isFeasible(context) }
}

/**
 * 判断一组领域策略是否全部认为宽度可切 /
 * Check if all domain policies consider the width cuttable
 *
 * @param V 数值类型 / Numeric value type
 * @param policies 领域策略列表 / Domain policy list
 * @param context 领域计算上下文 / Domain calculation context
 * @return true 表示所有策略都认为可切 / true if all policies consider cuttable
 */
fun <V : RealNumber<V>> allWidthFeasible(
    policies: List<Csp1dDomainPolicy<V>>,
    context: Csp1dDomainCalculationContext<V>
): Boolean {
    return policies.all { it.isWidthFeasible(context) }
}

/**
 * 从领域策略列表生成宽度可行性判断函数 / Generate width feasibility check function from domain policy list
 *
 * 只有声明 overridesWidthFeasibility = true 的 policy 才会参与宽度判断，
 * 替代原始 material.widthRange.canCut()。这避免了非宽度类 policy（设备兼容、业务可行性等）
 * 意外触发 canCut 替代，导致宽度边界被放宽。
 * 当没有 policy 声明 overridesWidthFeasibility = true 时，返回 null（使用默认 canCut 逻辑）。
 *
 * Only policies that declare overridesWidthFeasibility = true participate in width judgment,
 * replacing the original material.widthRange.canCut(). This prevents non-width policies
 * (device compatibility, business feasibility, etc.) from inadvertently triggering canCut
 * replacement and relaxing width boundaries.
 * When no policy declares overridesWidthFeasibility = true, returns null (use default canCut logic).
 *
 * @param V 数值类型 / Numeric value type
 * @param domainPolicies 领域策略列表 / Domain policy list
 * @param domainValueSample 领域数值样本 / Domain value sample
 * @return 宽度可行性判断函数，或 null 表示使用默认逻辑 / Width feasibility check function, or null for default logic
 */
fun <V : RealNumber<V>> widthFeasibilityCheckFromPolicies(
    domainPolicies: List<Csp1dDomainPolicy<V>>,
    domainValueSample: V
): ((Material<V>, Product<V>, Quantity<V>) -> Boolean)? {
    val widthOverridingPolicies = domainPolicies.filter { it.overridesWidthFeasibility }
    if (widthOverridingPolicies.isEmpty()) return null
    return { material: Material<V>, product: Product<V>, productWidth: Quantity<V> ->
        // 使用声明接管宽度判断的 domain policy 的 isWidthFeasible 替代原始 canCut
        // Use isWidthFeasible from policies that declared width override to replace original canCut
        val ctx = SimpleDomainCalculationContext(
            plan = CuttingPlan(
                id = "width-check-${material.id}-${product.id}",
                material = material,
                slices = listOf(CuttingPlanSlice(production = product, width = productWidth)),
                demandContributions = emptyList()
            ),
            planIndex = -1,
            domainValueSample = domainValueSample
        )
        allWidthFeasible(widthOverridingPolicies, ctx)
    }
}
