/**
 * 谓词 schema 渲染器测试
 * Predicate schema renderer tests
 *
 * 验证 PredicateSchemaRenderer 生成的代码结构正确性。
 * Verifies correctness of code structure generated by PredicateSchemaRenderer.
 */
package fuookami.ospf.kotlin.framework.persistence.expression.ksp

import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.DisplayName
import org.junit.jupiter.api.Test

@DisplayName("Predicate Schema Renderer Tests / 谓词 Schema 渲染器测试")
class PredicateSchemaRendererTest {
    /**
     * 验证渲染 schema 和 resolver 的代码结构
     * Verify rendered code structure for schema and resolver
     */
    @Test
    @DisplayName("Render schema and resolver / 渲染 schema 与 resolver")
    fun renderSchemaAndResolver() {
        val code = PredicateSchemaRenderer.render(
            PredicateSchemaModel(
                packageName = "example",
                entityName = "User",
                kotlinEntityName = "User",
                schemaName = "Users",
                generateResolver = true,
                generateColumnMapping = false,
                properties = listOf(
                    PredicateProperty("id", "user_id", "id"),
                    PredicateProperty("status", "user_status", "status"),
                    PredicateProperty("age", "age", "age")
                )
            )
        )

        assertTrue(code.contains("object Users : PredicateSchema<User>()"))
        assertTrue(code.contains("val status = field(User::status)"))
        assertTrue(code.contains("\"status\" -> \"user_status\""))
        assertFalse(code.contains("HasColumnMapping"))
        assertFalse(code.contains("columnMapping"))
        assertFalse(code.contains("createBinder"))
    }

    /**
     * 验证禁用 resolver 时不生成 resolver 属性
     * Verify resolver property is not generated when disabled
     */
    @Test
    @DisplayName("Skip resolver when disabled / 禁用时不生成 resolver")
    fun skipResolverWhenDisabled() {
        val code = PredicateSchemaRenderer.render(
            PredicateSchemaModel(
                packageName = "",
                entityName = "User",
                kotlinEntityName = "User",
                schemaName = "UserSchema",
                generateResolver = false,
                generateColumnMapping = false,
                properties = listOf(PredicateProperty("age", "age", "age"))
            )
        )

        assertFalse(code.contains("val resolver:"))
        assertTrue(code.contains("val age = field(User::age)"))
    }

    /**
     * 验证启用 columnMapping 时渲染列映射和 createBinder
     * Verify columnMapping and createBinder are rendered when enabled
     */
    @Test
    @DisplayName("Render columnMapping and createBinder when enabled / 启用时生成 columnMapping 与 createBinder")
    fun renderColumnMappingWhenEnabled() {
        val code = PredicateSchemaRenderer.render(
            PredicateSchemaModel(
                packageName = "example",
                entityName = "User",
                kotlinEntityName = "User",
                schemaName = "Users",
                generateResolver = true,
                generateColumnMapping = true,
                properties = listOf(
                    PredicateProperty("id", "user_id", "id"),
                    PredicateProperty("status", "user_status", "status")
                )
            )
        )

        assertTrue(code.contains("HasColumnMapping"))
        assertTrue(code.contains("override val columnMapping: Map<String, String> = mapOf("))
        assertTrue(code.contains("\"id\" to \"user_id\""))
        assertTrue(code.contains("\"status\" to \"user_status\""))
        assertTrue(code.contains("fun <C> createBinder(resolver: (String) -> C?): ColumnBinder<C>"))
        assertTrue(code.contains("val backendName = columnMapping[path] ?: path"))
        assertTrue(code.contains("import fuookami.ospf.kotlin.framework.persistence.expression.HasColumnMapping"))
        assertTrue(code.contains("import fuookami.ospf.kotlin.framework.persistence.expression.ColumnBinder"))
    }

    /**
     * 验证不生成 resolver 属性时仅生成 columnMapping
     * Verify only columnMapping is generated without resolver property
     */
    @Test
    @DisplayName("Render columnMapping without resolver property / 不生成 resolver 属性时仅生成 columnMapping")
    fun renderColumnMappingWithoutResolverProperty() {
        val code = PredicateSchemaRenderer.render(
            PredicateSchemaModel(
                packageName = "example",
                entityName = "User",
                kotlinEntityName = "User",
                schemaName = "Users",
                generateResolver = false,
                generateColumnMapping = true,
                properties = listOf(PredicateProperty("id", "user_id", "id"))
            )
        )

        assertFalse(code.contains("val resolver: (String) -> String?"))
        assertTrue(code.contains("HasColumnMapping"))
        assertTrue(code.contains("columnMapping"))
        assertTrue(code.contains("createBinder"))
    }

    /**
     * 验证 SnakeCase 命名策略渲染蛇形列名映射
     * Verify SnakeCase naming strategy renders snake_case column name mapping
     */
    @Test
    @DisplayName("Render columnMapping with SnakeCase naming strategy / SnakeCase 命名策略生成蛇形列名")
    fun renderColumnMappingWithSnakeCaseNamingStrategy() {
        val code = PredicateSchemaRenderer.render(
            PredicateSchemaModel(
                packageName = "example",
                entityName = "User",
                kotlinEntityName = "User",
                schemaName = "Users",
                generateResolver = false,
                generateColumnMapping = true,
                properties = listOf(
                    PredicateProperty("id", "id", "id"),
                    PredicateProperty("userName", "user_name", "userName"),
                    PredicateProperty("firstName", "first_name", "firstName")
                )
            )
        )

        assertTrue(code.contains("HasColumnMapping"))
        assertTrue(code.contains("\"id\" to \"id\""))
        assertTrue(code.contains("\"userName\" to \"user_name\""))
        assertTrue(code.contains("\"firstName\" to \"first_name\""))
    }

    /**
     * 验证 Identity 命名策略渲染恒等列名映射
     * Verify Identity naming strategy renders identity column name mapping
     */
    @Test
    @DisplayName("Render columnMapping with Identity naming strategy / Identity 命名策略生成恒等列名")
    fun renderColumnMappingWithIdentityNamingStrategy() {
        val code = PredicateSchemaRenderer.render(
            PredicateSchemaModel(
                packageName = "example",
                entityName = "User",
                kotlinEntityName = "User",
                schemaName = "Users",
                generateResolver = false,
                generateColumnMapping = true,
                properties = listOf(
                    PredicateProperty("id", "id", "id"),
                    PredicateProperty("userName", "userName", "userName")
                )
            )
        )

        assertTrue(code.contains("\"id\" to \"id\""))
        assertTrue(code.contains("\"userName\" to \"userName\""))
    }
}